# Generated by Django 6.0.2 on 2026-02-26 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="content",
            new_name="body",
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
