# Generated by Django 6.0.2 on 2026-02-27 10:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0002_rename_content_post_body_post_slug_alter_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="published_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
