# Generated by Django 6.0.2 on 2026-02-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0003_post_published_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_at"]},
        ),
        migrations.AddField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
