# Generated by Django 6.0.2 on 2026-02-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0004_alter_post_options_post_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("DF", "Draft"), ("PB", "Published")],
                default="DF",
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-published_at"], name="blogger_pos_publish_c5593b_idx"
            ),
        ),
    ]
