# Generated by Django 6.0.2 on 2026-03-19 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogger", "0006_post_author"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-publish"]},
        ),
        migrations.RemoveIndex(
            model_name="post",
            name="blogger_pos_publish_c5593b_idx",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="published_at",
            new_name="publish",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="updated_at",
            new_name="updated",
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, unique_for_date="publish"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["-publish"], name="blogger_pos_publish_8e9f0b_idx"
            ),
        ),
    ]
